### ISSUE TITLE
Crash on API < 26 

### ISSUE THREAD

**Issue by hivian** [amdelamar/jhash#24]
Hi,

I have a runtime crash on devices with API < 26
```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
        at com.amdelamar.jhash.util.HashUtils.encodeBase64(HashUtils.java:103)
        at com.amdelamar.jhash.Hash.create(Hash.java:182)
```

This class seems to be not available on older devices.

**Comment by amdelamar** [comment]
Are you running Java 8 or newer?

**Comment by amdelamar** [comment]
I assume you meant Android when you say "API < 26". Unfortunately, this lib is not tested on Android. 

Looks like `java.util.Base64` is not part of Android SDK. As mentioned by [this SO question.](https://stackoverflow.com/questions/48697766/android-studio-noclassdeffounderror-with-java-util-base64)

**Comment by hivian** [comment]
Yes I noticed your library was a java project and can't use android.util.Base64. I will find another way.

Thanks

**Comment by ThanosFisherman** [comment]
I am also in search of a hashing library that supports android api 21 and above. As a last resort I'm going to try Bouncy Castle. So far I've been trying to avoid it because it's too bloated but it should work fine nevertheless.

Here is the Android crypto compatibility doc 
https://developer.android.com/reference/javax/crypto/SecretKeyFactory

**Comment by mc51** [comment]
For me it works great on Android. Thanks @amdelamar for this great lib. 
To make it work, I have set minSdkVersion 26 and added the following to my build.gradle (app):

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
